/**
 * i2c bus sniffer pico.
 * Sniffer for an i2c bus using the PIO of Raspberry Pi Pico (RP2040/RP2350)
 * (C) Juan Schiavoni 2021-2026
 *
 * It is composed of 4 state machines that communicate through an IRQ and 
 * two auxiliary pins to encode the event. Three of them decode the 
 * START/STOP/DATA condition, and the last one serializes the events into 
 * a single FIFO; and reads the value of the 8-bit data plus the ACK.
 *
 * 2026 modernization:
 * - Lock-free Single-Producer Single-Consumer (SPSC) RAM FIFO, the same
 *   implementation proven in spi_sniffer_pio (fixes the inter-core sync issue).
 * - Optional INT (interrupt) channel: a fifth state machine on the second PIO
 *   block timestamps every edge of an open-drain, active-low interrupt line
 *   and interleaves it with the I2C events. Inert when the pin is left
 *   unconnected (input with pull-up, quiet high).
 * - Bus Pirate 5 support: 74HC595 cascade init (VREG rail, 10k pull-up
 *   network, analog MUX disabled) and IO buffers held in input mode, so the
 *   sniffer is passive by construction.
 * - Per-target PIO pin map generated by CMake from i2c_sniffer.pio.in.
 */
#include <stdio.h>
#include "pico/stdlib.h"
#include "hardware/pio.h"
#include "hardware/timer.h"
#include "hardware/clocks.h"
#include "i2c_sniffer.pio.h"
#include "pico/multicore.h"

#include "ram_fifo.h"

#undef PRINT_VAL

#undef PRINT_TIME_T
#undef PRINT_HEX_INDEX

// ==============================================================================
// GLOBAL HARDWARE CONFIGURATION PROFILE
// ==============================================================================
// TARGET_BUS_PIRATE_5 and INT_CAPTURE_EN are injected by CMake (see
// CMakeLists.txt); the ifndef guards provide the legacy defaults when the
// project is built outside the provided build system.
#ifndef TARGET_BUS_PIRATE_5
#define TARGET_BUS_PIRATE_5      0  // 1: Bus Pirate 5 hardware, 0: standard Pico
#endif

#ifndef INT_CAPTURE_EN
#define INT_CAPTURE_EN           1  // 0: build the exact 2021 single-bus sniffer
#endif

#if TARGET_BUS_PIRATE_5
    // Bus Pirate 5 (REV10) header mapping. The PIO pin map (SDA/SCL/EV) lives
    // in CMakeLists.txt: SDA = BUFIO7 (header IO7), SCL = BUFIO0 (header IO0),
    // and the internal event pins EV0/EV1 use GPIO16/GPIO17 (SPI_CDI/RGB_CDO,
    // both high-impedance sinks, safe for the PIO to drive).
    #define I2C_INT_PIN              9  // BUFIO1 = header IO1

    #define BP5_BUFDIR0_PIN          0 
    #define BP5_BUFDIR1_PIN          1
    #define BP5_BUFDIR2_PIN          2
    #define BP5_BUFDIR3_PIN          3
    #define BP5_BUFDIR4_PIN          4
    #define BP5_BUFDIR5_PIN          5
    #define BP5_BUFDIR6_PIN          6
    #define BP5_BUFDIR7_PIN          7

    // GPIO pins connected to the Bus Pirate 5 Shift Register (U501/U502)
    // Correct RP2040 GPIO mapping according to BP5 schematic (Sheet 4)
    #define BP5_SHIFT_CLK           18 // SPI_CLK -> SRCLK (U501/U502 pin 11)
    #define BP5_SHIFT_CDO           19 // SPI_CDO -> SER   (U501 pin 14)
    #define BP5_SHIFT_LATCH         20 // SHIFT_LATCH -> RCLK (U501/U502 pin 12)
    #define BP5_SHIFT_EN            21 // SHIFT_EN -> OE   (U501/U502 pin 13, Active LOW)

    // On-board SPI slaves that share GPIO18/19 with the 74HC595 cascade.
    #define BP5_DISPLAY_CS          25
    #define BP5_FLASH_CS            26
#else
    #define I2C_INT_PIN              4  // GP4, free on a standard Pico / Pico 2
    #define LED_PIN                 25
#endif

// INT event packing: bit 31 marks an INT event (I2C events never set it,
// their highest used bit is 12), bit 28 carries the line level after the edge.
#define EV_INT_TAG              0x80000000u
#define EV_INT_LEVEL            (1u << 28)

#define RAM_FIFO_SIZE           40000

volatile bool ram_fifo_overflow = false;
static volatile uint32_t fifo_max_level = 0;
static uint32_t fifo_overflow_counter = 0;

static char ascii_buff[64];
static uint32_t ascii_index = 0;

/*! \brief Converts a nibble to hexadecimal ascii..
 *  \ingroup main
 *
 * Quick routine to convert integers to hexadecimal characters.
 *
 * \return char (0,1,2,3,4,5,6,7,8,9,A,B,C,D,E,F).
 */
static inline char nibble_to_hex(uint8_t nibble) {
    nibble &= 0x0F;
  
    if (nibble > 9) {
        nibble += 'A' - '0' - 10;
    }

    return( nibble + '0' );
}

/*! \brief Print the buffered string.
 *  \ingroup main
 *
 * If the string buffer contains data, it sends it through the serial port.
 *
 * \param count quantity of items for FIFO
 * @return true if there is enough dynamic memory, false otherwise
 */
static inline void buff_print(void) {
    if (ascii_index > 0) {
        ascii_buff[ascii_index] = '\0';
        printf(ascii_buff); 
        ascii_index = 0;
    }
}

/*! \brief Insert a char in the buffered string.
 *  \ingroup main
 *
 * When the output is via USB CDC, the data is sent in packets of maximum 64 bytes every 1mS. 
 * As the decoding of the i2c frame is composed of more than one event (Start / Stop / Data) 
 * that are separated by a few uS, to optimize they are stored in buffer waiting for STOP, 
 * that the buffer is full, or that elapsed more than 100 uS since the last event.
 *
 * \param c char
 */
static inline void buff_putchar(char c) {
    // Reserve one byte for the NULL character.
    if (ascii_index >= sizeof(ascii_buff)-1) {
        buff_print();
    } 

    ascii_buff[ascii_index++] = c;
}

#if TARGET_BUS_PIRATE_5
    /**
     * @brief Writes a 16-bit word to the cascaded 74HC595 shift registers on Bus Pirate 5.
     * 
     * Hardware Cascade:
     * Data -> U501 (Bits 7..0) -> U502 (Bits 15..8)
     * - First 8 bits shifted out end up in U502.
     * - Last 8 bits shifted out remain in U501.
     * 
     * Bit 7 of U501 corresponds to PULLUP_EN:
     * - 0 = Pull-ups ENABLED (PMOS gates pulled to GND)
     * - 1 = Pull-ups DISABLED
     */
    static void bp5_shift_register_write_16(uint16_t value) {
        // Enable Shift Register outputs
        gpio_put(BP5_SHIFT_EN, 0);

        // Shift out 16 bits, MSB first
        for (int i = 15; i >= 0; i--) {
            bool bit = (value >> i) & 0x01;
            gpio_put(BP5_SHIFT_CDO, bit);

            // Clock pulse (SRCLK)
            gpio_put(BP5_SHIFT_CLK, 1);
            sleep_us(1);
            gpio_put(BP5_SHIFT_CLK, 0);
            sleep_us(1);
        }

        // Latch pulse (RCLK) to update hardware outputs
        gpio_put(BP5_SHIFT_LATCH, 1);
        sleep_us(1);
        gpio_put(BP5_SHIFT_LATCH, 0);
    }
    
    /**
     * @brief Initializes Bus Pirate 5 shift register control pins, enables the
     * 10k pull-up network and disables the analog MUX.
     */
    static void bp5_init_pullups(void) {
        gpio_init(BP5_SHIFT_CDO);
        gpio_set_dir(BP5_SHIFT_CDO, GPIO_OUT);
        gpio_put(BP5_SHIFT_CDO, 0);

        gpio_init(BP5_SHIFT_CLK);
        gpio_set_dir(BP5_SHIFT_CLK, GPIO_OUT);
        gpio_put(BP5_SHIFT_CLK, 0);

        gpio_init(BP5_SHIFT_LATCH);
        gpio_set_dir(BP5_SHIFT_LATCH, GPIO_OUT);
        gpio_put(BP5_SHIFT_LATCH, 0);

        gpio_init(BP5_SHIFT_EN);
        gpio_set_dir(BP5_SHIFT_EN, GPIO_OUT);
        gpio_put(BP5_SHIFT_EN, 0); // Active LOW

        // Word layout:
        // Bits 15..8 (U502): 0x00
        // Bits 7..0  (U501): 0x00 -> Bit 7 (PULLUP_EN) = 0 (Enables 10k Pull-ups)
        // Word 0x1041:
        // Bit 9  (CURRENT_EN) = 0 -> Enables VREG / VREF_VOUT 3.3V rail
        // Bit 7  (PULLUP_EN)  = 0 -> Enables 10k PMOS pull-ups
        // Bit 6  (DISP_RESET) = 1 -> Release LCD reset
        // Bit 0  (AMUX_EN)    = 1 -> Disable analog MUX (Active LOW)
        bp5_shift_register_write_16(0x1041);
    }

    /**
     * @brief Keeps the on-board SPI slaves (NAND flash and LCD) deselected.
     *
     * The NAND flash and the LCD share GPIO18/19 with the 74HC595 cascade, so
     * the bit-banged shift-register traffic reaches them. Driving both chip
     * selects high makes that traffic invisible to them. This also protects
     * GPIO16 (SPI_CDI), which the sniffer reuses as the PIO event pin EV0:
     * with the NAND deselected its data output stays in high impedance.
     */
    static void bp5_deselect_spi_slaves(void) {
        gpio_init(BP5_DISPLAY_CS);
        gpio_set_dir(BP5_DISPLAY_CS, GPIO_OUT);
        gpio_put(BP5_DISPLAY_CS, 1);

        gpio_init(BP5_FLASH_CS);
        gpio_set_dir(BP5_FLASH_CS, GPIO_OUT);
        gpio_put(BP5_FLASH_CS, 1);
    }
#endif

/**
 * @brief Configures global hardware pins and Bus Pirate 5 logic buffers.
 */
static void init_pins(void) {
#ifdef LED_PIN
    // The LED is used to indicate that the board has initialized successfully (ON), 
    // flashes when there is activity on the i2c bus, and turns off when it detects 
    // a RAM overflow.
    gpio_init(LED_PIN);
    gpio_set_dir(LED_PIN, GPIO_OUT);
#endif

#if TARGET_BUS_PIRATE_5    
    uint bp5_pins[] = {
        BP5_BUFDIR0_PIN, BP5_BUFDIR1_PIN, BP5_BUFDIR2_PIN, BP5_BUFDIR3_PIN,
        BP5_BUFDIR4_PIN, BP5_BUFDIR5_PIN, BP5_BUFDIR6_PIN, BP5_BUFDIR7_PIN,
    };
    
    // Configure Bus Pirate 5 buffer direction pins to LOW (input mode), so
    // the sniffer never drives the target bus: passive by construction.
    for (size_t i = 0; i < sizeof(bp5_pins) / sizeof(bp5_pins[0]); i++) {
        gpio_init(bp5_pins[i]);
        gpio_set_dir(bp5_pins[i], GPIO_OUT);
        gpio_put(bp5_pins[i], 0); 
    }

    // Deselect the on-board SPI slaves before bit-banging the shift register.
    bp5_deselect_spi_slaves();
    
    // Enable the VREG rail and the 10k pull-up network, disable the analog MUX.
    bp5_init_pullups();
#endif
}

/*! \brief Decode and print the captured events.
 *  \ingroup main
 *
 * CPU1 blocks waiting for CPU0 to send the events captured by the sniffer.
 *
 * \return void.
 */
void core1_print() {
    uint32_t val;
#ifdef PRINT_HEX_INDEX
    uint32_t capture_index = 0;
#endif
#if INT_CAPTURE_EN
    // The INT spy emits a (tag, timestamp) word pair per edge.
    bool int_ts_pending = false;
    bool int_level = false;
#endif
    bool overflow_reported = false;
    
    printf("i2c sniffer pico initialiced!\r\n");

    // Blocks the CPU waiting for FIFO captures from the core 0.
    while (true) {
        // It waits for the arrival of a new event for 100 uS, if it comes out due to timeout 
        // and there is a string stored in the buffer, it sends it.
        if (!multicore_fifo_pop_timeout_us(100, &val)) {
            buff_print();

            if (ram_fifo_overflow && !overflow_reported) {
                printf("[WARN] RAM FIFO overflow - capture loss (peak level %lu)\r\n",
                       (unsigned long)fifo_max_level);
                overflow_reported = true;
            }
            continue;
        }

#ifdef LED_PIN
        gpio_put(LED_PIN, false);
#endif

#if INT_CAPTURE_EN
        if (val & EV_INT_TAG) {
            int_level = (val & EV_INT_LEVEL) != 0;
            int_ts_pending = true;
            continue;                    // The next word carries the timestamp.
        }

        if (int_ts_pending) {
            buff_print();
            printf("[INT %s] t=%010lu\r\n", int_level ? "released" : "asserted",
                   (unsigned long)val);
            int_ts_pending = false;
            continue;
        }
#endif

        // The format of the uint32_t returned by the sniffer is composed of two event
        // code bits (EV1 = Bit12, EV0 = Bit11), and when it comes to data, the nine least
        // significant bits correspond to (ACK = Bit0), and the value 8 bits
        // where (B0 = Bit1 and B7 = Bit8).
        uint32_t ev_code = (val >> 10) & 0x03;
        uint8_t  data = ((val >> 1) & 0xFF);
        bool ack = (val & 1) ? false : true;
#ifdef PRINT_VAL
        printf("val: %x, ev_code: %x, data:%x, ack: %d \r\n", val, ev_code, data, ack);
#else
        if (ev_code == EV_START) {
#if defined(PRINT_TIME_T)
            printf("%010lu ", time_us_32());
#elif defined(PRINT_HEX_INDEX)
            printf("%08x ", capture_index++);
#endif
            buff_putchar('s');
        } else if (ev_code == EV_STOP) {
            buff_putchar('p');
            buff_putchar('\r');
            buff_putchar('\n');
            buff_print();
        } else if (ev_code == EV_DATA) {
            buff_putchar(nibble_to_hex(data>>4));
            buff_putchar(nibble_to_hex(data));
            buff_putchar(ack ? 'a' : 'n');
        } else {
            buff_putchar('u');
        }
#endif

#ifdef LED_PIN
        if (!ram_fifo_overflow) {
            gpio_put(LED_PIN, true);
        }
#endif
    }
}

int main()
{
    // Full speed for the PIO clock divider
    float div = 1;
    PIO pio = pio0;

    init_pins();
    
    // Initialize chosen serial port
    stdio_init_all();

    // Initialize the four state machines that decode the i2c bus states.
    uint sm_main = pio_claim_unused_sm(pio, true);
    uint offset_main = pio_add_program(pio, &i2c_main_program);
    i2c_main_program_init(pio, sm_main, offset_main, div);

    uint sm_data = pio_claim_unused_sm(pio, true);
    uint offset_data = pio_add_program(pio, &i2c_data_program);
    i2c_data_program_init(pio, sm_data, offset_data, div);

    uint sm_start = pio_claim_unused_sm(pio, true);
    uint offset_start = pio_add_program(pio, &i2c_start_program);
    i2c_start_program_init(pio, sm_start, offset_start, div);

    uint sm_stop = pio_claim_unused_sm(pio, true);
    uint offset_stop = pio_add_program(pio, &i2c_stop_program);
    i2c_stop_program_init(pio, sm_stop, offset_stop, div);

#if INT_CAPTURE_EN
    // The INT spy runs on the second PIO block, so it shares no resources
    // with the four state machines of the i2c sniffer. The same core 0 loop
    // drains both FIFOs, keeping a single producer for the SPSC RAM FIFO.
    PIO pio_int = pio1;
    uint sm_int = pio_claim_unused_sm(pio_int, true);
    uint offset_int = pio_add_program(pio_int, &int_spy_program);
    int_spy_program_init(pio_int, sm_int, offset_int, I2C_INT_PIN, div);
    pio_sm_set_enabled(pio_int, sm_int, true);
#endif

    // Start running our PIO program in the state machine
    pio_sm_set_enabled(pio, sm_main, true);
    pio_sm_set_enabled(pio, sm_start, true);
    pio_sm_set_enabled(pio, sm_stop, true);
    pio_sm_set_enabled(pio, sm_data, true);

    multicore_launch_core1(core1_print);

    // Initialize the ram FIFO with a depth of 40K captures.
    if (!ram_fifo_init(RAM_FIFO_SIZE)) {
        while(true);
    }

#ifdef LED_PIN
    gpio_put(LED_PIN, true);
#endif

    // CPU 0 drains the sniffer FIFOs (i2c events and INT edges) into the
    // lock-free SPSC RAM FIFO, and forwards the queued words to CPU 1 through
    // the multicore hardware FIFO whenever it has room. A single stream
    // keeps the temporal order between i2c frames and INT edges.
    while (true) {
        // Drain the i2c sniffer FIFO.
        while (pio_sm_get_rx_fifo_level(pio, sm_main) > 0) {
            if (!ram_fifo_set(pio_sm_get(pio, sm_main))) {
                fifo_overflow_counter++;
                ram_fifo_overflow = true;
            }
        }

#if INT_CAPTURE_EN
        // Drain the INT spy FIFO, expanding each edge into a (tag, timestamp)
        // word pair so the console can correlate it with the i2c frames.
        while (pio_sm_get_rx_fifo_level(pio_int, sm_int) > 0) {
            uint32_t level = pio_sm_get(pio_int, sm_int) & 1u;

            if (!ram_fifo_set(EV_INT_TAG | (level ? EV_INT_LEVEL : 0)) ||
                !ram_fifo_set(time_us_32())) {
                fifo_overflow_counter++;
                ram_fifo_overflow = true;
            }
        }
#endif

        // Forward the queued events to core 1 (one word per iteration, same
        // pacing as the 2021 design).
        if (multicore_fifo_wready() && !ram_fifo_is_empty()) {
            multicore_fifo_push_blocking(ram_fifo_get());
        }

        uint32_t current_level = ram_fifo_get_level();
        if (current_level > fifo_max_level) {
            fifo_max_level = current_level;
        }
    }
}
